# Generated by Django 3.1.5 on 2021-03-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_message_text', models.TextField(verbose_name='Latest Message')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Login')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='Message')),
                ('chat_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='chat_id', to='main.chat')),
                ('sender_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='main.user')),
                ('user_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='main.user')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='opponent_user_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='opponent_user_id', to='main.user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='chat_user_id', to='main.user'),
        ),
    ]
