# Generated by Django 3.1.5 on 2021-03-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wrong_attempts',
            field=models.IntegerField(default=0, verbose_name='Wrong_Attempts'),
        ),
    ]
